// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PrepareToInterview.Persistence.Contexts;

#nullable disable

namespace PrepareToInterview.Persistence.Migrations
{
    [DbContext(typeof(PrepareToInterviewAPIDbContext))]
    [Migration("20241231175546_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_answer");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_answer_question_id");

                    b.ToTable("answer", (string)null);
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("IconUrl")
                        .HasColumnType("text")
                        .HasColumnName("icon_url");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_category_parent_id");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.CategoryTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.HasKey("Id")
                        .HasName("pk_category_translation");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_category_translation_category_id");

                    b.ToTable("category_translation", (string)null);
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_comment");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_comment_question_id");

                    b.ToTable("comment", (string)null);
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("difficulty");

                    b.HasKey("Id")
                        .HasName("pk_question");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_question_category_id");

                    b.ToTable("question", (string)null);
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.QuestionTag", b =>
                {
                    b.Property<int>("QuestionID")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.Property<int>("TagID")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.HasKey("QuestionID", "TagID")
                        .HasName("pk_question_tag");

                    b.HasIndex("TagID")
                        .HasDatabaseName("ix_question_tag_tag_id");

                    b.ToTable("question_tag", (string)null);
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.QuestionTranslation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("LanguageCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language_code");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_question_translation");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_translation_question_id");

                    b.ToTable("question_translation", (string)null);
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_tag");

                    b.ToTable("tag", (string)null);
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Answer", b =>
                {
                    b.HasOne("PrepareToInterview.Domain.Entities.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_answer_question_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Category", b =>
                {
                    b.HasOne("PrepareToInterview.Domain.Entities.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .HasConstraintName("fk_category_category_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.CategoryTranslation", b =>
                {
                    b.HasOne("PrepareToInterview.Domain.Entities.Category", "Category")
                        .WithMany("CategoryTranslations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_translation_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Comment", b =>
                {
                    b.HasOne("PrepareToInterview.Domain.Entities.Question", "Question")
                        .WithMany("Comments")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_comment_question_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Question", b =>
                {
                    b.HasOne("PrepareToInterview.Domain.Entities.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_category_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.QuestionTag", b =>
                {
                    b.HasOne("PrepareToInterview.Domain.Entities.Question", "Question")
                        .WithMany("QuestionTags")
                        .HasForeignKey("QuestionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_tag_question_question_id");

                    b.HasOne("PrepareToInterview.Domain.Entities.Tag", "Tag")
                        .WithMany("QuestionTags")
                        .HasForeignKey("TagID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_tag_tag_tag_id");

                    b.Navigation("Question");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.QuestionTranslation", b =>
                {
                    b.HasOne("PrepareToInterview.Domain.Entities.Question", "Question")
                        .WithMany("QuestionTranslations")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_translation_question_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Category", b =>
                {
                    b.Navigation("CategoryTranslations");

                    b.Navigation("Children");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Comments");

                    b.Navigation("QuestionTags");

                    b.Navigation("QuestionTranslations");
                });

            modelBuilder.Entity("PrepareToInterview.Domain.Entities.Tag", b =>
                {
                    b.Navigation("QuestionTags");
                });
#pragma warning restore 612, 618
        }
    }
}
